steps:
 # ---------------------------------------------------
 # 1. Export GOOGLE_CREDENTIALS from Secret Manager
 #    & Terraform Init with GCS backend
 # ---------------------------------------------------
 - name: "hashicorp/terraform:latest"
   entrypoint: sh
   args:
     - -c
     - |
       echo "Fetching credentials from Secret Manager..."
       export GOOGLE_CREDENTIALS="$(gcloud secrets versions access latest --secret=cred)"
       echo "Running Terraform Init..."
       terraform init \
         -backend-config="bucket=terraform-logging" \
         -backend-config="prefix=terraform/state"
   dir: "terraform/"
 # ---------------------------------------------------
 # 2. Terraform Plan
 # ---------------------------------------------------
 - name: "hashicorp/terraform:latest"
   args:
     - plan
     - -out=tfplan
   dir: "terraform/"
 # ---------------------------------------------------
 # 3. Terraform Apply (optional)
 # ---------------------------------------------------
- name: "hashicorp/terraform:latest"
  args: ["apply", "-auto-approve", "tfplan"]
  dir: "terraform/"

substitutions:
  _TF_STATE_BUCKET: 'terraform-logging' # Define your GCS bucket for Terraform state
options:
  logging: CLOUD_LOGGING_ONLY
